//TODO: Menu
//new DesignPatternsGOF.Creational.FactoryMethod.Client().Execute();
//new DesignPatternsGOF.Creational.AbstractFactory.Client().Execute();
//new DesignPatternsGOF.Creational.Singleton.Client().Execute();
//new DesignPatternsGOF.Creational.Builder.Client().Execute();
//new DesignPatternsGOF.Creational.Prototype.Client().Execute();
//new DesignPatternsGOF.Structural.Adapter.Client().Execute();
//new DesignPatternsGOF.Structural.Flyweight.Client().Execute();
//new DesignPatternsGOF.Structural.Bridge.Client().Execute();
//new DesignPatternsGOF.Structural.Composite.Client().Execute();
new DesignPatternsGOF.Structural.Decorator.Client().Execute();